# yaml-language-server: $schema=http://json-schema.org/draft-07/schema
# SPDX-FileCopyrightText: 2014-2023 Institute for Automation of Complex Power Systems, RWTH Aachen University
# SPDX-License-Identifier: Apache-2.0
---
allOf:
- type: object
  properties:
    bits:
      type: integer
      default: 32
      description: Number of bits per signal. Must be one of 8, 16, 32, 64 or 128.

    endianess:
      type: string
      description: The endianess of the data.
      default: little
      enum:
      - big
      - little

    fake:
      type: boolean
      description: |
        Send and interpret the first three signals of each sample as the following header fields:
        - sequence number
        - timestamp seconds
        - timestamp nano-seconds

      default: false

- $ref: ../format.yaml
