# Dockerfile for VILLASnode development.
#
# This Dockerfile builds an image which contains all library dependencies
# and tools to build VILLASnode.
# However, VILLASnode itself it not part of the image.
#
# This image can be used for developing VILLASnode
# by running:
#   make docker
#
# @author Steffen Vogel <stvogel@eonerc.rwth-aachen.de>
# @copyright 2017, Institute for Automation of Complex Power Systems, EONERC
# @license GNU General Public License (version 3)
#
# VILLASnode
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
###################################################################################

# You can choose between Debian and Ubuntu here
FROM ubuntu:xenial
#FROM debian:jessie

MAINTAINER Steffen Vogel <stvogel@eonerc.rwth-aachen.de>

# Toolchain
RUN apt-get update && apt-get install -y \
	gcc g++ \
	pkg-config make cmake \
	autoconf automake autogen libtool \
	flex bison \
	texinfo \
	git curl tar \
	protobuf-compiler protobuf-c-compiler

# Several tools only needed for developement and testing
RUN apt-get update && apt-get install -y \
	doxygen dia graphviz \
	openssh-client \
	jq \
	iproute \
	python-pip \
	valgrind gdb gdbserver \
	xmlto asciidoctor

# Tools for debugging, coverage, profiling
RUN pip install \
	gcovr \
	protobuf

# Dependencies
RUN apt-get update && apt-get install -y \
	libsodium-dev \
	libpgm-dev \
	libssl-dev \
	libconfig-dev \
	libnl-3-dev libnl-route-3-dev \
	libcurl4-openssl-dev \
	libjansson-dev \
	libzmq3-dev \
	libnanomsg-dev \
	libprotobuf-c-dev

# Build & Install Criterion
COPY thirdparty/criterion /tmp/criterion
RUN mkdir -p /tmp/criterion/build && cd /tmp/criterion/build && cmake .. && make install && rm -rf /tmp/*

# Build & Install libxil
COPY thirdparty/libxil /tmp/libxil
RUN mkdir -p /tmp/libxil/build && cd /tmp/libxil/build && cmake .. && make install && rm -rf /tmp/*

# Build & Install libxil
COPY thirdparty/libwebsockets /tmp/libwebsockets
RUN mkdir -p /tmp/libwebsockets/build && cd /tmp/libwebsockets/build && cmake -DLWS_IPV6=1 -DLWS_WITH_STATIC=0 -DLWS_WITHOUT_TESTAPPS=1 -DLWS_WITH_HTTP2=1 .. && make install && rm -rf /tmp/*

# Expose ports for HTTP and WebSocket frontend
EXPOSE 80
EXPOSE 443

ENV LD_LIBRARY_PATH /usr/local/lib:/usr/local/lib64

# Workaround for libnl3's search path for netem distributions
RUN ln -s /usr/lib64/tc /usr/lib/tc

WORKDIR /villas
ENTRYPOINT bash
