## Main project Makefile
#
# The build system of this project is based on GNU Make and pkg-config
#
# To retain maintainability, the project is divided into multiple modules.
# Each module has its own Makefile which gets included.
#
# Please read "Recursive Make Considered Harmful" from Peter Miller
#  to understand the motivation for this structure.
#
# [1] http://aegis.sourceforge.net/auug97.pdf
#
# @author Steffen Vogel <stvogel@eonerc.rwth-aachen.de>
# @copyright 2017, Institute for Automation of Complex Power Systems, EONERC
# @license GNU General Public License (version 3)
#
# VILLASnode
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
###################################################################################

# Select modules
WITH_SRC       ?= 1
WITH_TOOLS     ?= 1
WITH_PLUGINS   ?= 1
WITH_TESTS     ?= 0
WITH_CLIENTS   ?= 0

# Select features
WITH_CONFIG    ?= 1
WITH_HOOKS     ?= 1
WITH_WEB       ?= 1
WITH_API       ?= 1
WITH_IO        ?= 1

# Select IO formats
WITH_FORMAT_PROTOBUF  ?= 1

# Select node-types
ifeq ($(PLATFORM),Linux)
	IS_LINUX = 1
else
	IS_LINUX = 0
endif

WITH_NODE_FPGA       ?= $(IS_LINUX)
WITH_NODE_CBUILDER   ?= $(IS_LINUX)
WITH_NODE_LOOPBACK   ?= $(IS_LINUX)
WITH_NODE_COMEDI	 ?= $(IS_LINUX)
WITH_NODE_TEST_RTT   ?= 1
WITH_NODE_FILE       ?= 1
WITH_NODE_SIGNAL     ?= 1
WITH_NODE_NGSI       ?= 1
WITH_NODE_WEBSOCKET  ?= 1
WITH_NODE_SOCKET     ?= 1
WITH_NODE_ZEROMQ     ?= 1
WITH_NODE_NANOMSG    ?= 1
WITH_NODE_SHMEM      ?= 1
WITH_NODE_STATS      ?= 1
WITH_NODE_INFLUXDB   ?= 1
WITH_NODE_AMQP       ?= 1
WITH_NODE_IEC61850   ?= 1
WITH_NODE_MQTT       ?= 1
WITH_NODE_INFINIBAND ?= 1
