logging = {
    level = "info"
}

fpgas = {
    zcu106 = {
        interface = "platform",
        ips = "/home/root/codebase/node/etc/fpga/zcu106_aurora_dino/zcu106_aurora_dino_240808-2.json", # Absolute path for remote debugging
        #ignore_ips = ["dino_dinoif_dac_0", "dino_dinoif_fast_nologic_0", "dino_registerif_0", "axi_iic_0"],
        polling = true,
    }
}

nodes = {
    fpga_0 = {
        type = "fpga",
        card = "zcu106"
        timestep = 0.000005
        # connect = ["loopback"]
        connect = ["dino<->dma"]
        in = {
            signals = ({ 
                    name="seqnum", 
                    type="integer",
                    unit=""
                    builtin = false,
                },
                { 
                    name="voltage",
                    type="float", 
                    unit="V"
                    builtin = false,
                })
            }
        lowLatencyMode = false,
    },

}

paths = (
    {
        builtin = false,
        in = "fpga_0.voltage"
        out = "fpga_0"
        #hooks = (
        #    {
        #        #type = "print"
        #        #output = "print_output_file.log"
        #        #format = "villas.human"
        #    })

    },
)



