# SPDX-FileCopyrightText: 2025 OPAL-RT Germany GmbH
# SPDX-License-Identifier: Apache-2.0

version = 1
SPDX-PackageName = "VILLASnode"
SPDX-PackageSupplier = "Steffen Vogel <post@steffenvogel.de>"
SPDX-PackageDownloadLocation = "https://fein-aachen.org/en/projects/villas-node/"

[[annotations]]
path = [
    "**.prefs",
    "**.vi",
    "**.opal",
    "**.dft",
    "**.sib",
    "**.json",
    "**.ipynb",
    "**_pb2.py",
    "doc/pictures/**",
    "doc/favicon.png",
    "clients/opal-rt/rtlab-asyncip/models/send_receive/eonerc_logo.png",
    "clients/rtds/**/**.txt",
    "clients/opal-rt/hypersim-ucm/**.ecf",
    "etc/labs/lab3.pcap",
    "tests/valgrind.supp",
    "packaging/archlinux/villas-node.install",
    "VILLASnode_paths.svg",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2018-2023, Institute for Automation of Complex Power Systems, RWTH Aachen University"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["flake.lock", "**.patch"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 OPAL-RT Germany GmbH"
SPDX-License-Identifier = "Apache-2.0"
