/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: lib/io/villas.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "lib/io/villas.pb-c.h"
void   villas__node__message__init
                     (Villas__Node__Message         *message)
{
  static Villas__Node__Message init_value = VILLAS__NODE__MESSAGE__INIT;
  *message = init_value;
}
size_t villas__node__message__get_packed_size
                     (const Villas__Node__Message *message)
{
  assert(message->base.descriptor == &villas__node__message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t villas__node__message__pack
                     (const Villas__Node__Message *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &villas__node__message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t villas__node__message__pack_to_buffer
                     (const Villas__Node__Message *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &villas__node__message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Villas__Node__Message *
       villas__node__message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Villas__Node__Message *)
     protobuf_c_message_unpack (&villas__node__message__descriptor,
                                allocator, len, data);
}
void   villas__node__message__free_unpacked
                     (Villas__Node__Message *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &villas__node__message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   villas__node__sample__init
                     (Villas__Node__Sample         *message)
{
  static Villas__Node__Sample init_value = VILLAS__NODE__SAMPLE__INIT;
  *message = init_value;
}
size_t villas__node__sample__get_packed_size
                     (const Villas__Node__Sample *message)
{
  assert(message->base.descriptor == &villas__node__sample__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t villas__node__sample__pack
                     (const Villas__Node__Sample *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &villas__node__sample__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t villas__node__sample__pack_to_buffer
                     (const Villas__Node__Sample *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &villas__node__sample__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Villas__Node__Sample *
       villas__node__sample__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Villas__Node__Sample *)
     protobuf_c_message_unpack (&villas__node__sample__descriptor,
                                allocator, len, data);
}
void   villas__node__sample__free_unpacked
                     (Villas__Node__Sample *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &villas__node__sample__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   villas__node__timestamp__init
                     (Villas__Node__Timestamp         *message)
{
  static Villas__Node__Timestamp init_value = VILLAS__NODE__TIMESTAMP__INIT;
  *message = init_value;
}
size_t villas__node__timestamp__get_packed_size
                     (const Villas__Node__Timestamp *message)
{
  assert(message->base.descriptor == &villas__node__timestamp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t villas__node__timestamp__pack
                     (const Villas__Node__Timestamp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &villas__node__timestamp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t villas__node__timestamp__pack_to_buffer
                     (const Villas__Node__Timestamp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &villas__node__timestamp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Villas__Node__Timestamp *
       villas__node__timestamp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Villas__Node__Timestamp *)
     protobuf_c_message_unpack (&villas__node__timestamp__descriptor,
                                allocator, len, data);
}
void   villas__node__timestamp__free_unpacked
                     (Villas__Node__Timestamp *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &villas__node__timestamp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   villas__node__value__init
                     (Villas__Node__Value         *message)
{
  static Villas__Node__Value init_value = VILLAS__NODE__VALUE__INIT;
  *message = init_value;
}
size_t villas__node__value__get_packed_size
                     (const Villas__Node__Value *message)
{
  assert(message->base.descriptor == &villas__node__value__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t villas__node__value__pack
                     (const Villas__Node__Value *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &villas__node__value__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t villas__node__value__pack_to_buffer
                     (const Villas__Node__Value *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &villas__node__value__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Villas__Node__Value *
       villas__node__value__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Villas__Node__Value *)
     protobuf_c_message_unpack (&villas__node__value__descriptor,
                                allocator, len, data);
}
void   villas__node__value__free_unpacked
                     (Villas__Node__Value *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &villas__node__value__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor villas__node__message__field_descriptors[1] =
{
  {
    "samples",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Villas__Node__Message, n_samples),
    offsetof(Villas__Node__Message, samples),
    &villas__node__sample__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned villas__node__message__field_indices_by_name[] = {
  0,   /* field[0] = samples */
};
static const ProtobufCIntRange villas__node__message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor villas__node__message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "villas.node.Message",
  "Message",
  "Villas__Node__Message",
  "villas.node",
  sizeof(Villas__Node__Message),
  1,
  villas__node__message__field_descriptors,
  villas__node__message__field_indices_by_name,
  1,  villas__node__message__number_ranges,
  (ProtobufCMessageInit) villas__node__message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue villas__node__sample__type__enum_values_by_number[3] =
{
  { "DATA", "VILLAS__NODE__SAMPLE__TYPE__DATA", 1 },
  { "START", "VILLAS__NODE__SAMPLE__TYPE__START", 2 },
  { "STOP", "VILLAS__NODE__SAMPLE__TYPE__STOP", 3 },
};
static const ProtobufCIntRange villas__node__sample__type__value_ranges[] = {
{1, 0},{0, 3}
};
static const ProtobufCEnumValueIndex villas__node__sample__type__enum_values_by_name[3] =
{
  { "DATA", 0 },
  { "START", 1 },
  { "STOP", 2 },
};
const ProtobufCEnumDescriptor villas__node__sample__type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "villas.node.Sample.Type",
  "Type",
  "Villas__Node__Sample__Type",
  "villas.node",
  3,
  villas__node__sample__type__enum_values_by_number,
  3,
  villas__node__sample__type__enum_values_by_name,
  1,
  villas__node__sample__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const Villas__Node__Sample__Type villas__node__sample__type__default_value = VILLAS__NODE__SAMPLE__TYPE__DATA;
static const ProtobufCFieldDescriptor villas__node__sample__field_descriptors[5] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Villas__Node__Sample, type),
    &villas__node__sample__type__descriptor,
    &villas__node__sample__type__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sequence",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Villas__Node__Sample, has_sequence),
    offsetof(Villas__Node__Sample, sequence),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Villas__Node__Sample, has_id),
    offsetof(Villas__Node__Sample, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Villas__Node__Sample, timestamp),
    &villas__node__timestamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "values",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Villas__Node__Sample, n_values),
    offsetof(Villas__Node__Sample, values),
    &villas__node__value__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned villas__node__sample__field_indices_by_name[] = {
  2,   /* field[2] = id */
  1,   /* field[1] = sequence */
  3,   /* field[3] = timestamp */
  0,   /* field[0] = type */
  4,   /* field[4] = values */
};
static const ProtobufCIntRange villas__node__sample__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor villas__node__sample__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "villas.node.Sample",
  "Sample",
  "Villas__Node__Sample",
  "villas.node",
  sizeof(Villas__Node__Sample),
  5,
  villas__node__sample__field_descriptors,
  villas__node__sample__field_indices_by_name,
  1,  villas__node__sample__number_ranges,
  (ProtobufCMessageInit) villas__node__sample__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor villas__node__timestamp__field_descriptors[2] =
{
  {
    "sec",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Villas__Node__Timestamp, sec),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nsec",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Villas__Node__Timestamp, nsec),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned villas__node__timestamp__field_indices_by_name[] = {
  1,   /* field[1] = nsec */
  0,   /* field[0] = sec */
};
static const ProtobufCIntRange villas__node__timestamp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor villas__node__timestamp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "villas.node.Timestamp",
  "Timestamp",
  "Villas__Node__Timestamp",
  "villas.node",
  sizeof(Villas__Node__Timestamp),
  2,
  villas__node__timestamp__field_descriptors,
  villas__node__timestamp__field_indices_by_name,
  1,  villas__node__timestamp__number_ranges,
  (ProtobufCMessageInit) villas__node__timestamp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor villas__node__value__field_descriptors[2] =
{
  {
    "f",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Villas__Node__Value, value_case),
    offsetof(Villas__Node__Value, f),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "i",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Villas__Node__Value, value_case),
    offsetof(Villas__Node__Value, i),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned villas__node__value__field_indices_by_name[] = {
  0,   /* field[0] = f */
  1,   /* field[1] = i */
};
static const ProtobufCIntRange villas__node__value__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor villas__node__value__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "villas.node.Value",
  "Value",
  "Villas__Node__Value",
  "villas.node",
  sizeof(Villas__Node__Value),
  2,
  villas__node__value__field_descriptors,
  villas__node__value__field_indices_by_name,
  1,  villas__node__value__number_ranges,
  (ProtobufCMessageInit) villas__node__value__init,
  NULL,NULL,NULL    /* reserved[123] */
};
