set MATLAB=C:\Program Files (x86)\MATLAB\R2013a
make -f send_receive_1_sm_model.mk  EXT_MODE=0 EXTMODE_STATIC_ALLOC=0 TMW_EXTMODE_TESTING=0 EXTMODE_STATIC_ALLOC_SIZE=1000000 EXTMODE_TRANSPORT=0 MAT_FILE=1
