# yaml-language-server: $schema=http://json-schema.org/draft-07/schema
# SPDX-FileCopyrightText: 2023 OPAL-RT Germany GmbH
# SPDX-License-Identifier: Apache-2.0
---
allOf:
- type: object
  required:
    - uri
    - mode
    - interval
    - algorithm
  properties:
    uri:
      description: The output file for digests.
      example: digest.txt
      type: string
      format: uri

    algorithm:
      description: The algorithm used for calculating digests.
      example: sha256
      type: string

- $ref: ../hook.yaml
