# yaml-language-server: $schema=http://json-schema.org/draft-07/schema
# SPDX-FileCopyrightText: 2023 OPAL-RT Germany GmbH
# SPDX-License-Identifier: Apache-2.0
---
allOf:
- type: object
  properties:
    trigger:
      description: The trigger for new frames.
      type: string
      default: timestamp
      enum:
      - sequence
      - timestamp

    interval:
      description: The interval in which frames are annotated.
      default: "1s"
      $ref: ../../duration.yaml

- $ref: ../hook.yaml
