# yaml-language-server: $schema=http://json-schema.org/draft-07/schema
# SPDX-FileCopyrightText: 2014-2023 Institute for Automation of Complex Power Systems, RWTH Aachen University
# SPDX-License-Identifier: Apache-2.0
---
allOf:
- type: object
  properties: 
    samples:
      type: integer
      description: The number of samples which should be dropped by this hook after a start or restart of the node/path.
    seconds:
      type: number
      description: The number of seconds for which this hook should initially drop samples after a start or restart of the node/path.

- $ref: ../hook.yaml
