# See https://redoc.ly/docs/cli/configuration/ for more information.
#
# SPDX-FileCopyrightText: 2014-2023 Institute for Automation of Complex Power Systems, RWTH Aachen University
# SPDX-License-Identifier: Apache-2.0
---
apiDefinitions:
  main: openapi/openapi.yaml
lint:
  extends:
  - recommended
  rules:
    no-unused-components: warning
referenceDocs:
  htmlTemplate: ./index.html
  theme:
    colors:
      primary:
        main: "#32329f"
