# yaml-language-server: $schema=http://json-schema.org/draft-07/schema
# SPDX-FileCopyrightText: 2014-2023 Institute for Automation of Complex Power Systems, RWTH Aachen University
# SPDX-License-Identifier: Apache-2.0
---
type: object
properties:
  enabled:
    type: boolean
    default: true
    title: Enable HTTP/WebSocket server
    description: |
      When set to `false`, the built-in HTTP & WebSocket server is disabled and will not listen on any port.

  port:
    type: integer
    default: 8080
    title: Listening port
    description: |
      The TCP port number on which the HTTP & WebSocket server listens.
      Defaults to 80 when running as root, otherwise 8080.

  ssl_cert:
    type: string
    title: SSL Certificate Path
    description: |
      The public x509 certificate used for server-side SSL encryption.

    example: /etc/ssl/certs/mycert.pem

  ssl_private_key:
    type: string
    title: SSL Private Key Path
    description: |
      The private x509 key used for server-side SSL encryption.

    example: /etc/ssl/private/mykey.pem

additionalProperties: false
