# SPDX-FileCopyrightText: 2014-2026 Institute for Automation of Complex Power Systems, RWTH Aachen University
# SPDX-License-Identifier: Apache-2.0

nodes = {
    fmu_node = {
        type = "fmu"
        # Path to FMU file (.fmu)
        fmu_path = "/workspaces/node/fmu_temp/asine.fmu"
        fmu_unpack_path = "/workspaces/node/fmu_temp/fmu_asine"
        fmu_write_first = true
        stop_time = 10.0
        start_time = 0.0
        step_size = 0.2

        in = {
            signals = (
                { name = "in1", type = "float" }
            )
        }

        out = {
            signals = (
                { name = "out1", type = "float" },
            )
        }
    }
}
