# SPDX-FileCopyrightText: 2014-2023 Institute for Automation of Complex Power Systems, RWTH Aachen University
# SPDX-License-Identifier: Apache-2.0

nodes = {
    file_output = {
        type = "file"
        # format = "csv"
        uri = "/workspaces/node/fmu_temp/output.dat"
        out = {

        }
    },

    signal_node = {
        type = "signal.v2"
        rate = 100.0
        realtime = true

        limit = 100

        in = {
            signals = (
                { name = "sine1",   signal = "sine",   amplitude = 1, frequency = 100   },
                # { name = "in2",   signal = "constant", amplitude = 1  },
            )
        }
    },
    fmu_node = {
        type = "fmu"
        # Path to fmu file
        fmu_path = "/workspaces/node/fmu_temp/asine.fmu"
        fmu_unpack_path = "/workspaces/node/fmu_temp/fmu_asine"
        fmu_writefirst = true
        stopTime = 10.0
        startTime = 0.0
        stepSize = 0.2

        in = {
            signals = (
                {name = "In1", type = "float"}
            )
        }

        out = {
            signals = (
                {name = "Out1", type = "float"},
            )
        }
    }
}

paths = (
    {
        in = "signal_node",
        out = "fmu_node"
    },
    {
        in = "fmu_node",
        out = "file_output"
    },
)
