# SPDX-FileCopyrightText: 2014-2023 Institute for Automation of Complex Power Systems, RWTH Aachen University
# SPDX-License-Identifier: Apache-2.0

nodes = {
    opal_async_node1 = {
        type = "opal.async"

        ### The following settings are specific to the opal node-type!! ###

        # The Send/Recv ID of the RT-Lab OpAsyncSend/Recv blocks.
        id = 1

        in = {
            # Send a confirmation to the Simulink model that signals have been received and processed.
            reply = false

            hooks = (
                "stats"
            )
        }
    }
}
