# Dockerfile for cross-compilation in Docker targeting the Raspberyy Pi.
#
# @author Steffen Vogel <stvogel@eonerc.rwth-aachen.de>
# @copyright 2014-2020, Institute for Automation of Complex Power Systems, EONERC
# @license GNU General Public License (version 3)
#
# VILLASnode
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
###################################################################################

FROM balenalib/rpi-raspbian:buster

ARG GIT_REV=unknown
ARG GIT_BRANCH=unknown
ARG VERSION=unknown
ARG VARIANT=unknown

# Toolchain
RUN apt-get update && \
    apt-get install -y \
	autoconf automake libtool cmake \
	pkg-config make gcc g++\
	git curl wget tar bzip2 \
	protobuf-compiler protobuf-c-compiler

# Dependencies
RUN apt-get update && \
    apt-get install -y\
	libssl-dev \
	libprotobuf-dev \
	libprotobuf-c-dev \
	uuid-dev \
	libconfig-dev \
	libnl-3-dev libnl-route-3-dev \
	libcurl4-openssl-dev \
	libjansson-dev \
	libzmq3-dev \
	libnanomsg-dev \
	librabbitmq-dev \
	libmosquitto-dev \
	libcomedi-dev \
	librdmacm-dev \
	libre-dev \
	libusb-1.0-0-dev

ENV CC=gcc
ENV CXX=g++

# Add CMake install dir to PATH
ENV PATH="usr/local/bin:${PATH}"

# Build & Install fmtlib
RUN cd /tmp && \
	git clone --recursive https://github.com/fmtlib/fmt.git && \
	mkdir -p fmt/build && cd fmt/build && \
	git checkout 5.2.0 && \
	cmake -DBUILD_SHARED_LIBS=1 .. && make -j$(nproc) install && \
	rm -rf /tmp/*

# Build & Install spdlog
RUN cd /tmp && \
	git clone --recursive https://github.com/gabime/spdlog.git && \
	mkdir -p spdlog/build && cd spdlog/build && \
	git checkout v1.3.1 && \
	cmake -DCMAKE_BUILD_TYPE=Release -DSPDLOG_FMT_EXTERNAL=1 -DSPDLOG_BUILD_BENCH=OFF .. && make -j$(nproc) install && \
	rm -rf /tmp/*

# Build & Install libwebsockets
RUN cd /tmp && \
	git clone -b v3.1-stable https://github.com/warmcat/libwebsockets && \
	mkdir -p libwebsockets/build && cd libwebsockets/build && \
	cmake -DLWS_WITHOUT_TESTAPPS=ON .. && make -j$(nproc) install && \
	rm -rf /tmp/*

# Build & Install libiec61850
RUN cd /tmp && \
	git clone -b v1.3.1 https://github.com/mz-automation/libiec61850 && \
	mkdir -p libiec61850/build && cd libiec61850/build && \
	cmake .. && make -j$(nproc) install && \
	rm -rf /tmp/*

RUN cd /tmp && \
	git clone -b rpm https://github.com/stv0g/uldaq && \
	cd uldaq && \
	autoreconf -i && ./configure --enable-examples=no && \
	make -j$(nproc) install && \
	rm -rf /tmp/*

# Expose ports for HTTP and WebSocket frontend
EXPOSE 80
EXPOSE 443

ENV LD_LIBRARY_PATH /usr/local/lib

WORKDIR /villas
ENTRYPOINT bash

LABEL \
	org.label-schema.schema-version="1.0" \
	org.label-schema.name="VILLASnode" \
	org.label-schema.license="GPL-3.0" \
	org.label-schema.vcs-ref="$GIT_REV" \
	org.label-schema.vcs-branch="$GIT_BRANCH" \
	org.label-schema.version="$VERSION" \
	org.label-schema.variant="$VARIANT" \
	org.label-schema.vendor="Institute for Automation of Complex Power Systems, RWTH Aachen University" \
	org.label-schema.author.name="Steffen Vogel" \
	org.label-schema.author.email="stvogel@eonerc.rwth-aachen.de" \
	org.label-schema.description="A image containing all build-time dependencies for VILLASnode based on Raspbian" \
	org.label-schema.url="http://fein-aachen.org/projects/villas-framework/" \
	org.label-schema.vcs-url="https://git.rwth-aachen.de/VILLASframework/VILLASnode" \
	org.label-schema.usage="https://villas.fein-aachen.org/doc/node-installation.html#node-installation-docker"
