# Dockerfile for VILLASnode development.
#
# This Dockerfile builds an image which contains all library dependencies
# and tools to build VILLASnode.
# However, VILLASnode itself it not part of the image.
#
# This image can be used for developing VILLASnode
# by running:
#   make docker-dev
#
# @author Steffen Vogel <stvogel@eonerc.rwth-aachen.de>
# @copyright 2014-2020, Institute for Automation of Complex Power Systems, EONERC
# @license GNU General Public License (version 3)
#
# VILLASnode
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
###################################################################################

FROM fedora:32

ARG GIT_REV=unknown
ARG GIT_BRANCH=unknown
ARG VERSION=unknown
ARG VARIANT=unknown

# Toolchain
RUN dnf -y install \
	gcc gcc-c++ \
	pkgconfig cmake make \
	autoconf automake autogen libtool \
	texinfo git mercurial curl tar \
	flex bison rpmdevtools \
	protobuf-compiler protobuf-c-compiler \
	libtool

# Several tools only needed for developement and testing
RUN dnf -y install \
	doxygen dia graphviz \
	openssh-clients \
	rpmdevtools rpm-build \
	jq nmap-ncat \
	iproute \
	python-pip \
	valgrind gdb gdb-gdbserver \
	cppcheck \
	xmlto dblatex rubygem-asciidoctor \
	psmisc procps-ng \
	rabbitmq-server mosquitto

# Tools for debugging, coverage, profiling
RUN pip install \
	gcovr \
	protobuf \
	flake8

# Dependencies
RUN dnf -y install \
	openssl-devel \
	libuuid-devel \
	libconfig-devel \
	libwebsockets-devel \
	libcurl-devel \
	jansson-devel \
	spdlog-devel \
	fmt-devel \
	libnl3-devel \
	graphviz-devel \
	protobuf-devel \
	protobuf-c-devel \
	zeromq-devel \
	nanomsg-devel \
	librabbitmq-devel \
	mosquitto-devel \
	libibverbs-devel \
	librdmacm-devel \
	libusb-devel

# Add local and 64-bit locations to linker paths
RUN echo /usr/local/lib   >> /etc/ld.so.conf && \
    echo /usr/local/lib64 >> /etc/ld.so.conf

ENV VARIANT=fedora
ENV ARCH=x86_64
ENV TRIPLET=x86_64-linux-gnu

# Install unpackaged dependencies from source
ADD packaging/deps.sh /
RUN bash deps.sh
RUN ldconfig

# Workaround for libnl3's search path for netem distributions
RUN ln -s /usr/lib64/tc /usr/lib/tc

# Expose ports for HTTP and WebSocket frontend
EXPOSE 80
EXPOSE 443

WORKDIR /villas
ENTRYPOINT bash

LABEL \
	org.label-schema.schema-version="1.0" \
	org.label-schema.name="VILLASnode" \
	org.label-schema.license="GPL-3.0" \
	org.label-schema.vcs-ref="$GIT_REV" \
	org.label-schema.vcs-branch="$GIT_BRANCH" \
	org.label-schema.version="$VERSION" \
	org.label-schema.variant="$VARIANT" \
	org.label-schema.vendor="Institute for Automation of Complex Power Systems, RWTH Aachen University" \
	org.label-schema.author.name="Steffen Vogel" \
	org.label-schema.author.email="stvogel@eonerc.rwth-aachen.de" \
	org.label-schema.description="A image containing all build-time dependencies for VILLASnode based on Fedora" \
	org.label-schema.url="http://fein-aachen.org/projects/villas-framework/" \
	org.label-schema.vcs-url="https://git.rwth-aachen.de/acs/public/villas/node" \
	org.label-schema.usage="https://villas.fein-aachen.org/doc/node-installation.html#node-installation-docker"
