# Dockerfile for VILLASnode development.
#
# This Dockerfile builds an image which contains all library dependencies
# and tools to build VILLASnode.
# However, VILLASnode itself it not part of the image.
#
# This image can be used for developing VILLASnode
# by running:
#   make docker
#
# @author Steffen Vogel <stvogel@eonerc.rwth-aachen.de>
# @copyright 2014-2020, Institute for Automation of Complex Power Systems, EONERC
# @license GNU General Public License (version 3)
#
# VILLASnode
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
###################################################################################

# This is a Centos 7 image including the devtoolset-7 for a more recenter toolchain
# See: https://www.softwarecollections.org/en/scls/rhscl/devtoolset-7/
FROM registry.centos.org/centos/devtoolset-7-toolchain-centos7

ARG GIT_REV=unknown
ARG GIT_BRANCH=unknown
ARG VERSION=unknown
ARG VARIANT=unknown

# Some of the dependencies are only available in our own repo
ADD https://packages.fein-aachen.org/redhat/fein.repo /etc/yum.repos.d/

USER root

# Enable Extra Packages for Enterprise Linux (EPEL) repo
RUN yum -y install epel-release

# Toolchain
RUN yum -y install \
	devtoolset-7-toolchain \
	pkgconfig make cmake3 \
	autoconf automake autogen libtool \
	flex bison \
	texinfo git mercurial curl tar \
	protobuf-compiler protobuf-c-compiler

# Several tools only needed for developement and testing
RUN yum -y install \
	doxygen dia graphviz \
	openssh-clients \
	rpmdevtools rpm-build \
	jq netcat \
	iproute \
	python-pip \
	valgrind gdb gdb-gdbserver \
	xmlto rubygem-asciidoctor \
	rabbitmq-server mosquitto

# Tools for debugging, coverage, profiling
RUN pip install \
	gcovr \
	protobuf

# Dependencies
RUN yum -y install \
	openssl-devel \
	protobuf-devel \
	protobuf-c-devel \
	libuuid-devel \
	libconfig-devel \
	libnl3-devel \
	libcurl-devel \
	jansson-devel \
	libwebsockets-devel \
	zeromq-devel \
	nanomsg \
	librabbitmq-devel \
	mosquitto-devel \
	libibverbs-devel \
	librdmacm-devel \
	re-devel \
	libusb1-devel

# Build & Install fmtlib
RUN cd /tmp && \
	git clone --recursive https://github.com/fmtlib/fmt.git && \
	mkdir -p fmt/build && cd fmt/build && \
	git checkout 5.2.0 && \
	cmake3 -DBUILD_SHARED_LIBS=1 .. && make -j$(nproc) install && \
	rm -rf /tmp/fmt

# Build & Install spdlog
RUN cd /tmp && \
	git clone --recursive https://github.com/gabime/spdlog.git && \
	mkdir -p spdlog/build && cd spdlog/build && \
	git checkout v1.3.1 && \
	cmake3 -DCMAKE_BUILD_TYPE=Release -DSPDLOG_FMT_EXTERNAL=1 -DSPDLOG_BUILD_BENCH=OFF .. && make -j$(nproc) install && \
	rm -rf /tmp/spdlog

# Build & Install Criterion
RUN cd /tmp && \
	git clone --recursive https://github.com/Snaipe/Criterion && \
	mkdir -p Criterion/build && cd Criterion/build && \
	git checkout v2.3.3 && \
	cmake3 -DCMAKE_INSTALL_LIBDIR=/usr/local/lib64 .. && make install && \
	rm -rf /tmp/*

# Build & Install libwebsockets
RUN cd /tmp && \
	git clone -b v3.1-stable https://github.com/warmcat/libwebsockets && \
	mkdir -p libwebsockets/build && cd libwebsockets/build && \
	cmake3 -DCMAKE_INSTALL_LIBDIR=/usr/local/lib64 -DLWS_WITHOUT_TESTAPPS=ON .. && make -j$(nproc) install && \
	rm -rf /tmp/libwebsockets

# Build & Install libiec61850
RUN cd /tmp && \
	git clone -b v1.3.1 https://github.com/mz-automation/libiec61850 && \
	mkdir -p libiec61850/build && cd libiec61850/build && \
	cmake3 -DCMAKE_INSTALL_LIBDIR=/usr/local/lib64 .. && make -j$(nproc) install && \
	rm -rf /tmp/libiec61850

# Build & Install uldaq
RUN cd /tmp && \
	git clone -b rpm https://github.com/stv0g/uldaq && \
	cd uldaq && \
	autoreconf -i && ./configure --enable-examples=no && \
	make -j$(nproc) install && \
	rm -rf /tmp/uldaq

# Build & Install EtherLab
RUN cd /tmp && \
	hg clone --branch stable-1.5 http://hg.code.sf.net/p/etherlabmaster/code etherlab && \
	cd etherlab && \
	./bootstrap && ./configure --enable-userlib=yes --enable-kernel=no --enable-tool=no && \
	make -j$(nproc) install && \
	rm -rf /tmp/etherlab

# Workaround for libnl3's search path for netem distributions
RUN ln -s /usr/lib64/tc /usr/lib/tc

# Expose ports for HTTP and WebSocket frontend
EXPOSE 80
EXPOSE 443

ENV LD_LIBRARY_PATH /usr/local/lib:/usr/local/lib64

WORKDIR /villas
ENTRYPOINT scl enable devtoolset-7 bash

LABEL \
	org.label-schema.schema-version="1.0" \
	org.label-schema.name="VILLASnode" \
	org.label-schema.license="GPL-3.0" \
	org.label-schema.vcs-ref="$GIT_REV" \
	org.label-schema.vcs-branch="$GIT_BRANCH" \
	org.label-schema.version="$VERSION" \
	org.label-schema.variant="$VARIANT" \
	org.label-schema.vendor="Institute for Automation of Complex Power Systems, RWTH Aachen University" \
	org.label-schema.author.name="Steffen Vogel" \
	org.label-schema.author.email="stvogel@eonerc.rwth-aachen.de" \
	org.label-schema.description="A image containing all build-time dependencies for VILLASnode based on CentOS" \
	org.label-schema.url="http://fein-aachen.org/projects/villas-framework/" \
	org.label-schema.vcs-url="https://git.rwth-aachen.de/VILLASframework/VILLASnode" \
	org.label-schema.usage="https://villas.fein-aachen.org/doc/node-installation.html#node-installation-docker"
