# yaml-language-server: $schema=http://json-schema.org/draft-07/schema
---

allOf:
- type: object
  required:
  - interface
  properties:
    in:
      type: object
      properties:
        signals:
          type: array
          items:
            $ref: ../iec61850_signal.yaml

    out:
      type: object
      properties:
        required:
        - signals
        - svid
        signals:
          type: array
          items:
            $ref: ../iec61850_signal.yaml
        
        svid:
          type: string

        confrev:
          type: integer

        smpmod:
          type: string
          enum:
          - per_nominal_period
          - samples_per_second
          - seconds_per_sample

        smprate:
          type: integer

        vlan_id:
          type: integer

        vlan_priority:
          type: integer

          

    interface:
      type: string
      description: Name of network interface to/from which this node will publish/subscribe for SV frames.

    app_id:
      type: integer

    dst_address:
      type: string

- $ref: ../node.yaml
