# yaml-language-server: $schema=http://json-schema.org/draft-07/schema
# SPDX-FileCopyrightText: 2014-2023 Institute for Automation of Complex Power Systems, RWTH Aachen University
# SPDX-License-Identifier: Apache-2.0
---
allOf:
- type: object
  properties:
    realtime:
      type: boolean
      default: true
      description: Pace the generation of samples by the `rate` setting.

    limit:
      type: integer
      default: 0
      description: Stop the node after the provided number of samples.

    rate:
      type: number
      description: The rate at which the samples are generated if operating in real-time mode (See `realtime` option).

    monitor_missed:
      type: boolean
      default: false
      description: Raise warnings if the signal generator fails to operate in real-time due to missed deadlines.

    in:
      type: object
      required:
      - signals
      properties:
        signals:
          type: array
          items:
            $ref: ./signals/signal_v2_signal.yaml

- $ref: ../node.yaml
