# SPDX-FileCopyrightText: 2026 Institute for Automation of Complex Power Systems, RWTH Aachen University
# SPDX-License-Identifier: Apache-2.0

@include "hook-nodes.conf"

paths = (
    {
        in = "signal_node"
        out = "file_node"

        hooks = (
            {
                type = "pps_ts"
                signal = "pps"
                time_source = "sample"
                threshold = 0.5
            }
        )
    }
)
