pkg_check_modules(PC_PROTOBUFC QUIET libprotobuf-c)
set(PROTOBUFC_DEFINITIONS ${PC_PROTOBUFC_CFLAGS_OTHER})

find_path(PROTOBUFC_INCLUDE_DIR google/protobuf-c/protobuf-c.h 
	HINTS ${PC_PROTOBUFC_INCLUDEDIR} ${PC_PROTOBUFC_INCLUDE_DIRS}
	PATH_SUFFIXES libprotobuf-c)

find_library(PROTOBUFC_LIBRARY NAMES protobuf-c 
	HINTS ${PC_PROTOBUFC_LIBDIR}
	${PC_PROTOBUFC_LIBRARY_DIRS})

find_program(PROTOBUFC_COMPILER protoc-c)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(libprotobuf-c DEFAULT_MSG
	PROTOBUFC_LIBRARY PROTOBUFC_INCLUDE_DIR PROTOBUFC_COMPILER)
mark_as_advanced(PROTOBUFC PROTOBUFC_INCLUDE_DIR PROTOBUFC_LIBRARY)

set(PROTOBUFC_LIBRARIES ${PROTOBUFC_LIBRARY})
set(PROTOBUFC_INCLUDE_DIRS ${PROTOBUFC_INCLUDE_DIR})
