---

type: object
properties:
  iec_type:
    type: string
    enum:
    - boolean
    - int8
    - int16
    - int32
    - int64
    - int8u
    - int16u
    - int32u
    - int64u
    - float32
    - float64
    - enumerated
    - coded_enum
    - octet_string
    - visible_string
    - objectname
    - objectreference
    - timestamp
    - entrytime
    - bitstring
