# SPDX-FileCopyrightText: 2025 OPAL-RT Germany GmbH
# SPDX-License-Identifier: Apache-2.0

---
name: Draft PDF

on:
  push:
    paths:
        - paper/**
        - .github/workflows/paper.yaml

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build draft PDF
      uses: openjournals/openjournals-draft-action@v1.0
      with:
        journal: joss
        paper-path: paper/paper.md

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: paper
        path: paper/paper.pdf
